# Generated by Django 3.0 on 2019-12-15 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=220, null=True)),
                ('language', models.CharField(blank=True, max_length=220, null=True)),
                ('source', models.URLField(blank=True, max_length=1000)),
                ('strategic_anno', models.NullBooleanField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=220, null=True)),
                ('shortcut_key', models.CharField(blank=True, max_length=220, null=True)),
                ('color', models.CharField(blank=True, max_length=220, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpacyLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.TextField(blank=True, null=True)),
                ('iso', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=220, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('datasets', models.ManyToManyField(blank=True, to='cadet_app.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=220, null=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=220, null=True)),
                ('review', models.CharField(choices=[('NR', 'No review required'), ('SR', 'Single required'), ('MR', 'Multiple annotators')], default='NR', max_length=2)),
                ('annotators', models.ManyToManyField(blank=True, related_name='annotators', to=settings.AUTH_USER_MODEL)),
                ('datasets', models.ManyToManyField(blank=True, default=None, to='cadet_app.Dataset')),
                ('editors', models.ManyToManyField(related_name='editors', to=settings.AUTH_USER_MODEL)),
                ('owners', models.ManyToManyField(related_name='owners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabelGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=220, null=True)),
                ('labels', models.ManyToManyField(to='cadet_app.Label')),
            ],
        ),
        migrations.AddField(
            model_name='label',
            name='values',
            field=models.ManyToManyField(to='cadet_app.Value'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='spacy_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadet_app.SpacyLanguage'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='texts',
            field=models.ManyToManyField(to='cadet_app.Text'),
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_char', models.IntegerField(default=None)),
                ('approved', models.BooleanField(default=None)),
                ('auto_generated', models.BooleanField(default=None)),
                ('annotation_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadet_app.AnnotationType')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_author', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadet_app.Dataset')),
                ('labels', models.ManyToManyField(to='cadet_app.Label')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadet_app.Project')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_text', to='cadet_app.Text')),
            ],
        ),
    ]
