# Generated by Django 2.2.7 on 2019-12-05 20:03

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=220, null=True)),
                ('language', models.CharField(blank=True, max_length=220, null=True)),
                ('source', models.URLField(blank=True, max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=220, null=True)),
                ('value', models.CharField(blank=True, max_length=220, null=True)),
                ('shortcut_key', models.CharField(blank=True, max_length=220, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('datasets', models.ManyToManyField(to='cadet_app.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=220, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=220, null=True)),
                ('language_object', models.CharField(blank=True, max_length=220, null=True)),
                ('spaCy_model', models.CharField(blank=True, max_length=220, null=True)),
                ('review', models.CharField(choices=[('NR', 'No review required'), ('SR', 'Single required'), ('MR', 'Multiple annotators')], default='NR', max_length=2)),
                ('annotators', models.ManyToManyField(related_name='annotators', to=settings.AUTH_USER_MODEL)),
                ('datasets', models.ManyToManyField(to='cadet_app.Dataset')),
                ('editors', models.ManyToManyField(related_name='editors', to=settings.AUTH_USER_MODEL)),
                ('owners', models.ManyToManyField(related_name='owners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabelGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=220, null=True)),
                ('labels', models.ManyToManyField(to='cadet_app.Label')),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='texts',
            field=models.ManyToManyField(to='cadet_app.Text'),
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadet_app.Project')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadet_app.Text')),
            ],
        ),
    ]
